version: "3.8"
services:
    app:
        build: ./app/
        container_name: app
        restart: always
        ports:
        - 5000:5000
        links:
        - db
        networks:
        - python-postgres

    db:
        build: ./database/
        container_name: mydb
        restart: always
        ports:
        - 5432:5432
        environment:
        - POSTGRES_HOST_AUTH_METHOD=trust
        - PGDATA='/var/lib/postgresql/data'
        volumes:
        - /var/postgres/data:/var/lib/postgres/data
        - /tmp/bkups/blog/postgres/db:/tmp
        networks:
        - python-postgres

networks:
  python-postgres:
       driver : bridge
       name: python-postgres
